apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
  ALLOW_PLAINTEXT_LISTENER: "yes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      name: kafka
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        envFrom:
          - configMapRef:
              name: kafka-config
---
kind: Service
apiVersion: v1
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
  type: NodePort
