apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-config
data:
  ALLOW_ANONYMOUS_LOGIN: "yes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk
  labels:
    app: zk
spec:
  selector:
    matchLabels:
      app: zk
  template:
    metadata:
      name: zk
      labels:
        app: zk
    spec:
      containers:
      - name: zk
        image: bitnami/zookeeper:latest
        envFrom:
          - configMapRef:
              name: zk-config
---
  kind: Service
  apiVersion: v1
  metadata:
    name: zk
  spec:
    selector:
      app: zk
    ports:
      - port: 2181
    type: NodePort
