apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: superset
  labels:
    app: superset
  annotations:
    openshift.io/image.insecureRepository: "true"
spec:
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      name: superset
      labels:
        app: superset
    spec:
      containers:
      - name: superset
      #  image: superset
        image: nexus.ext.cetic.be:8083/cetic/bdf-superset
      #  imagePullPolicy: Never
        imagePullPolicy: IfNotPresent
        env:
          - name: ADMIN_PWD
            value: admin
          - name: ADMIN_MAIL
            value: admin@admin.com
          - name: ADMIN_LAST_NAME
            value: admin
          - name: ADMIN_FIRST_NAME
            value: user
          - value: ADMIN_USER
            name: admin
      imagePullSecrets:
      - name: docker-creds
      #status:
      #  dockerImageRepository: nexus.ext.cetic.be:8083
---
apiVersion: v1
kind: Service
metadata:
  name: superset
  labels:
    app: superset
spec:
  selector:
    app: superset
  ports:
    - port: 8088
  type: NodePort
