apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  labels:
    app: superset
spec:
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      name: superset
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: superset
        imagePullPolicy: Never
        env:
          - name: ADMIN_PWD
            value: admin
          - name: ADMIN_MAIL
            value: admin@admin.com
          - name: ADMIN_LAST_NAME
            value: admin
          - name: ADMIN_FIRST_NAME
            value: user
          - value: ADMIN_USER
            name: admin
---
apiVersion: v1
kind: Service
metadata:
  name: superset
  labels:
    app: superset
spec:
  selector:
    app: superset
  ports:
    - port: 8088
  type: NodePort
