apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_SERVICE: postgres-wh
  POSTGRES_PORT: "5432"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-wh
  labels:
    app: postgres-wh
spec:
  selector:
    matchLabels:
      app: postgres-wh
  template:
    metadata:
      name: postgres-wh
      labels:
        app: postgres-wh
    spec:
      containers:
      - name: postgres
        image: postgres:10.5
        envFrom:
          - configMapRef:
              name: postgres-config
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-wh
spec:
  selector:
    app: postgres-wh
  ports:
    - port: 5432
  type: NodePort
