---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nifi
  labels:
    app: nifi
spec:
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      name: nifi
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: apache/nifi:latest
        env:
        - name: NIFI_WEB_HTTP_PORT
          value: "9090"
        volumeMounts:
        - name: config-nifi
          mountPath: /opt/nifi/nifi-current/conf/bootstrap.conf
          subPath: bootstrap.conf
          ## See Error with subPath https://github.com/openshift/origin/issues/16951
        resources:
          requests:
            memory: "1000Mi"
            cpu: "500m"
          limits:
            memory: "3000Mi"
            cpu: "1000m"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "mkdir /opt/nifi/psql; wget -P /opt/nifi/psql https://jdbc.postgresql.org/download/postgresql-42.2.5.jar"]
      volumes:
        - name: config-nifi
          configMap:
            name: config-nifi-bootstrap
            items:
              - key: bootstrap.conf
                path: bootstrap.conf
---
kind: Service
apiVersion: v1
metadata:
  name: nifi
spec:
  selector:
    app: nifi
  ports:
    - port: 80
      targetPort: 9090
  type: LoadBalancer
