---
# Default values for FADI.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
spark:
  enabled: true
  Master:
    Name: spark-master
  WebUi:
    Name: spark-webui
  Worker:
    Name: spark-worker
  Zeppelin:
    Name: spark-zeppelin
    Replicas: 0

superset:
  enabled: true
  persistence:
    enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    annotations: {}
    path: /
    hosts: [fadi-superset.minikube]
    
postgresql:
  enabled: true
  persistence:
    enabled: true

minio:
  enabled: true
  persistence:
    enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    path: /minio
    hosts: [fadi.minikube]

grafana:
  enabled: true
  image:
    tag: 6.3.0-beta2
  #LoadBalancer service
  service:
    type: ClusterIP
  ingress:
    enabled: true
    path: /grafana/
    hosts:
      - fadi.minikube
  grafana.ini:
    server:
      root_url: http://fadi.minikube/grafana/
      serve_from_sub_path: true
  # Enable persistence
  persistence:
    enabled: true
  # Administrator credentials when not using an existing secret (see below)
  adminUser: admin
  adminPassword: password

jupyterhub:
  enabled: true
  proxy:
    secretToken: 'af83775ec3bfaf0507ce596df51d491e7ed54450adc454038fa7405495465f19'
  hub:
    baseUrl: /jupyterhub
    db:
      type: sqlite-memory
  rbac:
    enabled: true
  singleuser:
    storage:
      type: none
  # Defines the default image
    image:
      name: jupyter/minimal-notebook
      tag: 7d427e7a4dde
    profileList:
      - display_name: "Minimal environment"
        description: "To avoid too much bells and whistles: Python."
        default: true
      - display_name: "Datascience environment"
        description: "If you want the additional bells and whistles: Python, R, and Julia."
        kubespawner_override:
          image: jupyter/datascience-notebook:7d427e7a4dde
      - display_name: "Spark environment"
        description: "The Jupyter Stacks spark image"
        kubespawner_override:
          image: jupyter/all-spark-notebook:latest
  auth:
    type: dummy
    whitelist:
      users:
    admin:
      access: true
      users:
        - admin
    dummy:
      password: 'password'
    ldap:
      dn:
        search: {}
        user: {}
      user: {}
    state:
      enabled: false
      cryptoKey:
  prePuller:
    hook:
      enabled: false
  ingress:
    enabled: true
    hosts: [fadi.minikube]
    pathSuffix: ''

nifi:
  enabled: true
  service:
    loadBalancer:
      enabled: true
      type: ClusterIP
  ingress:
    enabled: true
    annotations: {}
    tls: []
    hosts: 
      - fadi.minikube
    path: /nifi

pgadmin:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    annotations: {traefik.ingress.kubernetes.io/rule-type: Path}
    path: /pgadmin
    hosts:
      - fadi.minikube
  pgadmin:
    scriptname: /pgadmin
