name: fadi_ci
on: [push]
jobs:
  k8s:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s: [v1.17.0]
    steps:
    - name: Ready minikube
      uses: manusa/actions-setup-minikube@v1.1.0
      with:
        minikube version: 'v1.12.0'
        kubernetes version: ${{ matrix.k8s }}
        start args: '--cpus 6 --memory 8192 --addons=ingress'
    - name: Checkout code
      uses: actions/checkout@v1
    - name: configure context
      run: kubectl config set-context minikube
    - name: check addons
      run: minikube addons list
    - name: Install FADI
      run: cd ./helm && ./deploy.sh
    - name: Configure namespace
      run: kubectl config set-context minikube --namespace fadi
    - name: Check pods
      run: kubectl get pods
    - name: Check deployments
      run: kubectl get deployments
    - name: Check fadi-adminer deployment status
      run: kubectl rollout status deployment fadi-adminer
    - name: Check fadi-grafana deployment status
      run: kubectl rollout status deployment fadi-grafana
    - name: Check fadi-nifi deployment status
      run: kubectl wait --for=condition=Ready pod/fadi-nifi-0 --timeout=10m  
    - name: Set adminer service
      run: |
        touch tests/.env
        echo ADMINER_URL=$(minikube service -n fadi fadi-adminer --url) >> tests/.env
    - name: Set grafana service
      run: |
        echo GRAFANA_URL=$(minikube service -n fadi fadi-grafana --url) >> tests/.env   
    - name: Set nifi service
      run: |
        echo NIFI_URL=$(minikube service -n fadi fadi-nifi --url) >> tests/.env 
    - name: Check .env
      run: cat tests/.env
    - name: install dependencies 
      run: cd ./tests && sudo npm install
    - name: launch functional tests
      run: cd ./tests && sudo npm run test
    - name: Display structure of tests files
      run: ls 
      working-directory: tests/files
    - name: delete minikube cluster
      run: minikube delete